manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.0
      import: 
        name-allowlist:
          - cmsis_6
          - cmsis
          - hal_stm32
          - mcuboot

    # Verknüpfung deines lokalen UDS-Modul-Ordners:
    - name: uds_server
      path: modules/lib/uds_server
      url: /home/borob/zephyr_workspace/uds
      revision: main

  self:
    path: uds_app_project
